update jetpack-compose to 1.0.0-beta08 by increaing kotlin compiler to 1.5.10
Recompile against latest Jetpack Compose due to NoSuchMethodError

Fixes: #1098